CREATE TABLE users1 (
    id INT AUTO_INCREMENT PRIMARY KEY,
fio VARCHAR(255) NOT NULL,
tel VARCHAR(50) NOT NULL,
email VARCHAR(255) NOT NULL,
soob TEXT,
login VARCHAR(100) NOT NULL UNIQUE,
password_hash VARCHAR(255) NOT NULL
);
